// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';

export function ChildGoBack():Promise<void>;

export function ChildGoForward():Promise<void>;

export function ChildReload():Promise<void>;

export function IsMacOS():Promise<boolean>;

export function AddTrustedHost(arg1:string):Promise<state.AppState>;

export function AdjustZoom(arg1:number):Promise<state.AppState>;

export function DeleteUrl(arg1:string):Promise<state.AppState>;

export function GetState():Promise<state.AppState>;

export function GetWindowState():Promise<string>;

export function MoveUrl(arg1:string,arg2:number):Promise<state.AppState>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function RemoveTrustedHost(arg1:string):Promise<state.AppState>;

export function SetAlias(arg1:string,arg2:string):Promise<state.AppState>;

export function SwitchToUrl(arg1:string):Promise<state.AppState>;

export function ToggleFullscreen():Promise<boolean>;

export function ToggleGridMode():Promise<state.AppState>;

export function ToggleKeepScreenOn():Promise<state.AppState>;

export function ToggleMaximize():Promise<boolean>;

export function TogglePin(arg1:string):Promise<state.AppState>;

export function TogglePreload(arg1:string):Promise<state.AppState>;

export function ToggleRotation(arg1:string):Promise<state.AppState>;

export function ToggleScrollLock():Promise<state.AppState>;

export function ToggleShowRotationBtns():Promise<state.AppState>;

export function ToggleStatusBar():Promise<state.AppState>;
