// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrustedHost(arg1) {
  return window['go']['main']['App']['AddTrustedHost'](arg1);
}

export function AdjustZoom(arg1) {
  return window['go']['main']['App']['AdjustZoom'](arg1);
}

export function DeleteUrl(arg1) {
  return window['go']['main']['App']['DeleteUrl'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function RemoveTrustedHost(arg1) {
  return window['go']['main']['App']['RemoveTrustedHost'](arg1);
}

export function SetAlias(arg1, arg2) {
  return window['go']['main']['App']['SetAlias'](arg1, arg2);
}

export function SwitchToUrl(arg1) {
  return window['go']['main']['App']['SwitchToUrl'](arg1);
}

export function ToggleKeepScreenOn() {
  return window['go']['main']['App']['ToggleKeepScreenOn']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function TogglePreload(arg1) {
  return window['go']['main']['App']['TogglePreload'](arg1);
}

export function ToggleRotation(arg1) {
  return window['go']['main']['App']['ToggleRotation'](arg1);
}

export function ToggleShowRotationBtns() {
  return window['go']['main']['App']['ToggleShowRotationBtns']();
}

export function ToggleStatusBar() {
  return window['go']['main']['App']['ToggleStatusBar']();
}
