// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrustedHost(arg1) {
  return window['go']['main']['App']['AddTrustedHost'](arg1);
}

export function AdjustZoom(arg1) {
  return window['go']['main']['App']['AdjustZoom'](arg1);
}

export function DeleteUrl(arg1) {
  return window['go']['main']['App']['DeleteUrl'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function MoveUrl(arg1, arg2) {
  return window['go']['main']['App']['MoveUrl'](arg1, arg2);
}

export function RemoveTrustedHost(arg1) {
  return window['go']['main']['App']['RemoveTrustedHost'](arg1);
}

export function SetAlias(arg1, arg2) {
  return window['go']['main']['App']['SetAlias'](arg1, arg2);
}

export function SwitchToUrl(arg1) {
  return window['go']['main']['App']['SwitchToUrl'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleGridMode() {
  return window['go']['main']['App']['ToggleGridMode']();
}

export function ToggleKeepScreenOn() {
  return window['go']['main']['App']['ToggleKeepScreenOn']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function TogglePreload(arg1) {
  return window['go']['main']['App']['TogglePreload'](arg1);
}

export function ToggleRotation(arg1) {
  return window['go']['main']['App']['ToggleRotation'](arg1);
}

export function ToggleScrollLock() {
  return window['go']['main']['App']['ToggleScrollLock']();
}

export function ToggleShowRotationBtns() {
  return window['go']['main']['App']['ToggleShowRotationBtns']();
}

export function ToggleStatusBar() {
  return window['go']['main']['App']['ToggleStatusBar']();
}
